apiVersion: v1
kind: Secret
metadata:
  name: health-monitor
  annotations: {}
  labels:
    app: health-monitor
type: Opaque
data:
  ConnectionStrings__orleans-redis: IG9ybGVhbnMtcmVkaXMtbWFzdGVyLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==
  